### ISSUE TITLE
no-jquery/no-global-selector needs better description

### ISSUE THREAD

**Issue by tgr** [wikimedia/eslint-plugin-no-jquery#109]
#6 / #11 added `no-jquery/no-global-selector` ("Global selectors are not allowed") to force application code to confine selectors to the application area.

"Global selector" is a term I haven't heard outside of this error message, so I doubt many developers would understand what's meant, and often this is a legitimate pattern which makes guessing what the error is about even harder, so it could use a better description. Maybe something like "JQuery selectors should always use a context"?

**Comment by edg2s** [comment]
> "JQuery selectors should always use a context"?

This may be an improvement, but this still suggests the fix is always just to add a context, however I think the best solution is to keep the DOM node in memory when possible.

If the DOM node was not created by the app, then the rule should probably just be disabled for that line.

**Comment by Perhelion** [comment]
I don't understand why an ID-selector should be global or forbidden to use. For me this is clear false warning.

**Comment by edg2s** [comment]
"global" does not refer to ID's here, it refers to searching the entire DOM, as opposed to a small sub-tree. The rule is designed to encourage you to keep DOM nodes in memory, or search within a sub-tree to avoid picking up DOM nodes from other components (as was the cause of this bug: https://phabricator.wikimedia.org/T204749)

**Comment by edg2s** [comment]
> ID-selectors are the best possible selectors

That depends on context. They are certainly the fastest, but if you are writing a component that you may ever want to re-use they cause problems as they have to be unique.

This has happened in the past in MediaWiki with things that we thought would only ever occur once on the page (e.g. the Table of Contents), but with the visual editor we now need two versions of the TOC in the DOM.
