### ISSUE TITLE
Update deprecations rulesets

### ISSUE THREAD

**Issue by edg2s** [wikimedia/eslint-plugin-no-jquery#117]
jQuery deprecations are poorly documented, in various places you get different answers as to when a rule was deprecated. Is it when core is updated, or when jquery migrate is updated? And the docs at api.jquery.com are missing a lot of deprecations (e.g. all of 3.2).

Going by the release notes we are missing a few things:
3.3: https://blog.jquery.com/2018/01/19/jquery-3-3-0-a-fragrant-bouquet-of-deprecations-and-is-that-a-new-feature/
3.2: https://blog.jquery.com/2017/03/16/jquery-3-2-0-is-out/

Other info:
Task about 3.2/3.3 deprecations: https://github.com/jquery/api.jquery.com/issues/972

**Comment by stof** [comment]
I suggest basing that on when core is updated, rather than when jquery migrate catches up.
