### ISSUE TITLE
$.filter does not have a -util version

### ISSUE THREAD

**Issue by Paril** [wikimedia/eslint-plugin-no-jquery#141]
I'm looking to get rid of the utility functions, and $.filter seems to be the odd one out. $('a').filter('.some_class') is a fairly valid/often-used pattern, and as far as I can tell $.filter as a "util" function doesn't even exist. The documentation is a bit wrong on this one.

**Comment by edg2s** [comment]
`$.filter` is not documented but it does exist and is used internally by `$.fn.filter`. I can't imagine a situation where you'd want to disable the filter method but not the util (or vice versa).

**Comment by Paril** [comment]
You're right, I think I just misread something and must have thought it was replaceable in my usages!
