### ISSUE TITLE
Split off from dgraham/eslint-plugin-jquery and choose new name

### ISSUE THREAD

**Issue by edg2s** [wikimedia/eslint-plugin-no-jquery#58]
As we continue to diverge, and the dgraham/eslint-plugin-jquery project continues to bit-rot, it seems less likely we will ever merge back in, so it will probably just be better to break off and choose a unique name.

Proposals so far:
* `no-jquery`
* `jq`
* `avoid-jquery`
* `nojq`

**Comment by edg2s** [comment]
My current preference is `no-jquery`, it's fairly short, descriptive (all of our rules are currently no- rules) and `jq` may be an abbreviation people don't understand.

**Comment by jdforrester** [comment]
`no-jquery` works for me.

**Comment by Krinkle** [comment]
Note that if we use the `@wikimedia` prefix, we wouldn't have to use a different name per-se. If we do pick a different name, my only (mild) preference would be for it to not contain a dash so as to keep the convention of `eslint-plugin-name`.

**Comment by edg2s** [comment]
The problem with the `@wikimedia` prefix is we have to add it to every rule exception, so you get a load of:
```javascript
// eslint-disable-next-line @wikimedia/jquery/no-global-selector
$( '.myApp' )...
```
Also once we start cleaning up the lack of util/collection splits in more of the methods we are going to be left with a package that has less than 50% in common with upstream.

> my only (mild) preference would be for it to not contain a dash so as to keep the convention of `eslint-plugin-{name}`.

Does `eslint-plugin-no-jquery` not fit with the convention and work?

**Comment by Krinkle** [comment]
Yeah, I suppose it does. Just felt like it'd be neat to avoid dashes in the name, but don't mind me :)

**Comment by edg2s** [comment]
I've sent a support request to have our fork status removed. Once that is actioned I'll rename this repo to `eslint-plugin-no-jquery`. If this somehow breaks our npm dependency chain, I'll fork it back to `eslint-plugin-jquery` as a temporary alias.

**Comment by edg2s** [comment]
De-forking is done. Apparently renaming leaves behind a redirect as long as a new repo isn't created at the old name.
