### ISSUE TITLE
Better documentation of rules

### ISSUE THREAD

**Issue by jdforrester** [wikimedia/eslint-plugin-no-jquery#77]
* We should document each rule (in the README?)
* We should give explicit rationale as to why a particular rule is "bad" (//e.g.// more expensive than the native browser function, or can easily mask bugs where operating on `null`, or…)
* We should give "real-world" examples rather than just vague "use `Array.find()`".
* For the (currently one) rule where there are config options, we should have a way to explain why you'd care each way and have the examples as above.
* Moar?

**Comment by edg2s** [comment]
`no-global-selector` and `no-parse-html-literal` require more complex documentation, as they only match specific string arguments.

Also `no-sizzle`, `no-ready`, `no-on-ready`, `no-animate-toggle`, `no-ajax-events` are all non-standard.

If we wanted to be really fancy we could build docs from the unit tests.

**Comment by stof** [comment]
should the CI also detect when the documentation was not updated for changes ?

**Comment by edg2s** [comment]
Good point, filed #108.
